import type { IncomingMessage } from "node:http";
import type { Params } from "nestjs-pino";
import { newRequestId } from "./api-error.js";

/**
 * STRUCTURED LOGGING (ARCHITECTURE §10, remediation finding 5) — pino JSON lines with a
 * `request_id` on every request log and `tenant_id` bound once the ApiKeyGuard resolves it.
 * Extracted from the module wiring so the pieces are unit-testable without booting Nest.
 */

/** Headers whose VALUES must never reach a log line (secrets rule: prefixes only, never values). */
export const REDACTED_HEADER_PATHS = [
  "req.headers.authorization",
  'req.headers["x-operator-token"]',
  'req.headers["x-bff-token"]',
  'req.headers["x-webhook-token"]',
  'req.headers["cookie"]',
];

/**
 * The request target with any query string removed.
 *
 * pino-http's default `req` serializer logs `url` verbatim, query string included, and `redact`
 * only reaches header PATHS — so a secret carried in the query is written to the log on the SUCCESS
 * path, at info level, on every request. That is not hypothetical here: Arkesel delivery reports are
 * unsigned GETs that cannot set headers, so the ingress token travels as `?token=`, and every
 * callback would otherwise print `WEBHOOK_INGRESS_TOKEN` in full.
 *
 * The path is kept because it is what makes a log line useful; only the values are dropped. Named
 * rather than blanked so a reader can tell "no query" from "query withheld".
 */
export function stripQueryString(url: string | undefined): string {
  if (typeof url !== "string" || url.length === 0) return "";
  const start = url.indexOf("?");
  return start === -1 ? url : `${url.slice(0, start)}?[query-redacted]`;
}

/**
 * Request id: honor a well-formed inbound `x-request-id` (API Gateway / caller correlation),
 * otherwise mint our `req_…` id — the same shape the error envelope uses.
 */
export function resolveRequestId(
  req: Pick<IncomingMessage, "headers">,
): string {
  const inbound = req.headers["x-request-id"];
  const value = Array.isArray(inbound) ? inbound[0] : inbound;
  if (typeof value === "string" && /^[\w.-]{8,128}$/.test(value)) {
    return value;
  }
  return newRequestId();
}

/** The tenant the ApiKeyGuard attached, if the request got that far. */
export function requestTenantId(req: IncomingMessage): string | undefined {
  const tenant = (req as { tenant?: { id?: unknown } }).tenant;
  return typeof tenant?.id === "string" ? tenant.id : undefined;
}

/**
 * nestjs-pino module params — one place, testable pieces above. NOTE: the request id itself is
 * generated by the FastifyAdapter's `genReqId` (main.ts) — under the Fastify adapter, Fastify's
 * id wins over pino-http's, so configuring it here would be dead code.
 */
export function loggerParams(): Params {
  return {
    pinoHttp: {
      customProps: (req: IncomingMessage) => {
        const tenantId = requestTenantId(req);
        return tenantId === undefined ? {} : { tenant_id: tenantId };
      },
      redact: { paths: REDACTED_HEADER_PATHS, censor: "[redacted]" },
      // Mirrors pino-http's default req shape, minus the query string — see stripQueryString.
      serializers: {
        req: (req: IncomingMessage & { id?: unknown }) => ({
          id: req.id,
          method: req.method,
          url: stripQueryString(req.url),
          headers: req.headers,
        }),
      },
      // Health checks would otherwise dominate the log volume.
      autoLogging: {
        ignore: (req: IncomingMessage) => req.url === "/health",
      },
    },
  };
}
