import type { IncomingMessage } from "node:http";
import type { Params } from "nestjs-pino";
import { newRequestId } from "./api-error.js";

/**
 * STRUCTURED LOGGING (ARCHITECTURE §10, remediation finding 5) — pino JSON lines with a
 * `request_id` on every request log and `tenant_id` bound once the ApiKeyGuard resolves it.
 * Extracted from the module wiring so the pieces are unit-testable without booting Nest.
 */

/** Headers whose VALUES must never reach a log line (secrets rule: prefixes only, never values). */
export const REDACTED_HEADER_PATHS = [
  "req.headers.authorization",
  'req.headers["x-operator-token"]',
  'req.headers["x-bff-token"]',
  'req.headers["x-webhook-token"]',
  'req.headers["cookie"]',
];

/**
 * Request id: honor a well-formed inbound `x-request-id` (API Gateway / caller correlation),
 * otherwise mint our `req_…` id — the same shape the error envelope uses.
 */
export function resolveRequestId(
  req: Pick<IncomingMessage, "headers">,
): string {
  const inbound = req.headers["x-request-id"];
  const value = Array.isArray(inbound) ? inbound[0] : inbound;
  if (typeof value === "string" && /^[\w.-]{8,128}$/.test(value)) {
    return value;
  }
  return newRequestId();
}

/** The tenant the ApiKeyGuard attached, if the request got that far. */
export function requestTenantId(req: IncomingMessage): string | undefined {
  const tenant = (req as { tenant?: { id?: unknown } }).tenant;
  return typeof tenant?.id === "string" ? tenant.id : undefined;
}

/**
 * nestjs-pino module params — one place, testable pieces above. NOTE: the request id itself is
 * generated by the FastifyAdapter's `genReqId` (main.ts) — under the Fastify adapter, Fastify's
 * id wins over pino-http's, so configuring it here would be dead code.
 */
export function loggerParams(): Params {
  return {
    pinoHttp: {
      customProps: (req: IncomingMessage) => {
        const tenantId = requestTenantId(req);
        return tenantId === undefined ? {} : { tenant_id: tenantId };
      },
      redact: { paths: REDACTED_HEADER_PATHS, censor: "[redacted]" },
      // Health checks would otherwise dominate the log volume.
      autoLogging: {
        ignore: (req: IncomingMessage) => req.url === "/health",
      },
    },
  };
}
