import { whatsappSendRequest } from "@app/contracts";
import { NextResponse } from "next/server";
import { BffError } from "@/lib/server/api-client";
import {
  readDashboardSession,
  refreshDashboardSession,
} from "@/lib/server/auth";
import {
  bffFailure,
  bffForbidden,
  bffInvalidRequest,
  bffUnauthorized,
} from "@/lib/server/bff-error";
import { hasTrustedOrigin } from "@/lib/server/origin";
import {
  listWhatsappMessages,
  sendWhatsappMessage,
} from "@/lib/server/whatsapp-client";

/** WhatsApp log for the session's current environment (plan -> sandbox|live). Gated on read scope. */
export async function GET(request?: Request) {
  const session =
    (await readDashboardSession()) ?? (await refreshDashboardSession());
  if (!session) return bffUnauthorized("invalid_session", "Sign in again.");
  if (!session.permissions.includes("whatsapp:read")) {
    return bffForbidden(
      "insufficient_permission",
      "You don't have access to WhatsApp messages.",
    );
  }
  const env = session.plan === "sandbox" ? "sandbox" : "live";
  const searchParams = request
    ? new URL(request.url).searchParams
    : new URLSearchParams();
  try {
    return NextResponse.json(
      await listWhatsappMessages(session.orgId, env, {
        ...(searchParams.get("limit")
          ? { limit: searchParams.get("limit") ?? undefined }
          : {}),
        ...(searchParams.get("cursor")
          ? { cursor: searchParams.get("cursor") ?? undefined }
          : {}),
        ...(searchParams.get("status")
          ? { status: searchParams.get("status") ?? undefined }
          : {}),
      }),
    );
  } catch (error) {
    return bffError(error);
  }
}

/** Dashboard WhatsApp compose. Requires an Idempotency-Key generated by the browser per submit. */
export async function POST(request: Request) {
  if (!hasTrustedOrigin(request)) {
    return bffForbidden("invalid_origin", "Request rejected.");
  }
  const session =
    (await readDashboardSession()) ?? (await refreshDashboardSession());
  if (!session) return bffUnauthorized("invalid_session", "Sign in again.");
  if (!session.permissions.includes("whatsapp:send")) {
    return bffForbidden(
      "insufficient_permission",
      "You don't have access to send WhatsApp messages.",
    );
  }
  const parsed = whatsappSendRequest.safeParse(await request.json());
  if (!parsed.success) {
    return invalidRequest("The WhatsApp send request is invalid.");
  }
  const idempotencyKey = request.headers.get("idempotency-key")?.trim();
  if (!idempotencyKey) {
    return invalidRequest("An Idempotency-Key is required.");
  }
  const env = session.plan === "sandbox" ? "sandbox" : "live";
  try {
    return NextResponse.json(
      await sendWhatsappMessage(
        session.orgId,
        env,
        parsed.data,
        idempotencyKey,
      ),
    );
  } catch (error) {
    return bffError(error);
  }
}

function invalidRequest(message: string) {
  return bffInvalidRequest("invalid_whatsapp_request", message);
}

function bffError(error: unknown) {
  return error instanceof BffError
    ? NextResponse.json(error.payload, { status: error.status })
    : bffFailure("bff_error", "Request failed.");
}
