import { whatsappSendRequest } from "@app/contracts";
import { NextResponse } from "next/server";
import { BffError } from "@/lib/server/api-client";
import {
  readDashboardSession,
  refreshDashboardSession,
} from "@/lib/server/auth";
import { hasTrustedOrigin } from "@/lib/server/origin";
import {
  listWhatsappMessages,
  sendWhatsappMessage,
} from "@/lib/server/whatsapp-client";

/** WhatsApp log for the session's current environment (plan -> sandbox|live). Gated on read scope. */
export async function GET(request?: Request) {
  const session =
    (await readDashboardSession()) ?? (await refreshDashboardSession());
  if (!session) return authError("invalid_session", "Sign in again.", 401);
  if (!session.permissions.includes("whatsapp:read")) {
    return authError(
      "insufficient_permission",
      "You don't have access to WhatsApp messages.",
      403,
    );
  }
  const env = session.plan === "sandbox" ? "sandbox" : "live";
  const searchParams = request
    ? new URL(request.url).searchParams
    : new URLSearchParams();
  try {
    return NextResponse.json(
      await listWhatsappMessages(session.orgId, env, {
        ...(searchParams.get("limit")
          ? { limit: searchParams.get("limit") ?? undefined }
          : {}),
        ...(searchParams.get("cursor")
          ? { cursor: searchParams.get("cursor") ?? undefined }
          : {}),
      }),
    );
  } catch (error) {
    return bffError(error);
  }
}

/** Dashboard WhatsApp compose. Requires an Idempotency-Key generated by the browser per submit. */
export async function POST(request: Request) {
  if (!hasTrustedOrigin(request)) {
    return authError("invalid_origin", "Request rejected.", 403);
  }
  const session =
    (await readDashboardSession()) ?? (await refreshDashboardSession());
  if (!session) return authError("invalid_session", "Sign in again.", 401);
  if (!session.permissions.includes("whatsapp:send")) {
    return authError(
      "insufficient_permission",
      "You don't have access to send WhatsApp messages.",
      403,
    );
  }
  const parsed = whatsappSendRequest.safeParse(await request.json());
  if (!parsed.success) {
    return invalidRequest("The WhatsApp send request is invalid.");
  }
  const idempotencyKey = request.headers.get("idempotency-key")?.trim();
  if (!idempotencyKey) {
    return invalidRequest("An Idempotency-Key is required.");
  }
  const env = session.plan === "sandbox" ? "sandbox" : "live";
  try {
    return NextResponse.json(
      await sendWhatsappMessage(
        session.orgId,
        env,
        parsed.data,
        idempotencyKey,
      ),
    );
  } catch (error) {
    return bffError(error);
  }
}

function authError(code: string, message: string, status: number) {
  return NextResponse.json(
    { error: { type: "auth_error", code, message } },
    { status },
  );
}

function invalidRequest(message: string) {
  return NextResponse.json(
    {
      error: {
        type: "invalid_request_error",
        code: "invalid_whatsapp_request",
        message,
      },
    },
    { status: 400 },
  );
}

function bffError(error: unknown) {
  return error instanceof BffError
    ? NextResponse.json(error.payload, { status: error.status })
    : NextResponse.json(
        {
          error: {
            type: "api_error",
            code: "bff_error",
            message: "Request failed.",
          },
        },
        { status: 500 },
      );
}
