import type { DefinitionManifest, FieldSchema } from "./manifest.js";

export function generateCatalog(manifest: DefinitionManifest): string {
  const definitions = [...manifest.definitions].sort((left, right) =>
    left.key.localeCompare(right.key),
  );
  const messages = definitions
    .map((definition) => {
      const locales = [...definition.locales].sort().map(quote).join(" | ");
      const channels = definition.channels.map(quote).join(" | ");
      return [
        `    readonly ${quote(definition.key)}: {`,
        `      readonly data: ${renderField(definition.data_schema, 6)};`,
        `      readonly channels: ${channels};`,
        `      readonly locales: ${locales};`,
        "    };",
      ].join("\n");
    })
    .join("\n");
  return [
    "// Generated by @fabric-messaging/cli. Do not edit.",
    'import type { DefinitionCatalog } from "@fabric-messaging/sdk";',
    "",
    "export interface FabricCatalog extends DefinitionCatalog {",
    "  readonly generated: true;",
    `  readonly environment: ${quote(manifest.environment.type)};`,
    "  readonly messages: {",
    messages,
    "  };",
    "}",
    "",
    `export const fabricCatalogDigest = ${quote(manifest.compatibility_digest)};`,
    "",
  ].join("\n");
}

function renderField(schema: FieldSchema, indent: number): string {
  let result: string;
  if (schema.enum && schema.enum.length > 0) {
    result = schema.enum.map((value) => JSON.stringify(value)).join(" | ");
  } else if (schema.type === "string") {
    result = "string";
  } else if (schema.type === "number" || schema.type === "integer") {
    result = "number";
  } else if (schema.type === "boolean") {
    result = "boolean";
  } else if (schema.type === "array") {
    result = `ReadonlyArray<${renderField(schema.items ?? { type: "string" }, indent)}>`;
  } else {
    result = renderObject(schema, indent);
  }
  return schema.nullable ? `${result} | null` : result;
}

function renderObject(schema: FieldSchema, indent: number): string {
  const properties = Object.entries(schema.properties ?? {}).sort(
    ([left], [right]) => left.localeCompare(right),
  );
  if (properties.length === 0) return "Record<string, never>";
  const required = new Set(schema.required ?? []);
  const spaces = " ".repeat(indent);
  const closing = " ".repeat(Math.max(0, indent - 2));
  const lines = properties.map(
    ([name, field]) =>
      `${spaces}readonly ${quote(name)}${required.has(name) ? "" : "?"}: ${renderField(field, indent + 2)};`,
  );
  return `{\n${lines.join("\n")}\n${closing}}`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}
