import { sql } from "drizzle-orm";
import {
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import {
  type ApplicationId,
  type EnvironmentId,
  type TenantId,
  timestamps,
} from "./_shared.js";
import { applications, environments } from "./applications.js";

/**
 * TENANT WEBHOOKS + TRANSACTIONAL OUTBOX (ARCHITECTURE §4/§9, remediation finding 8).
 *
 * `outbox_events`: a domain event is INSERTed in the SAME transaction as the domain write
 * (message status change, top-up credit) — the classic transactional-outbox seam. If the tx
 * rolls back, the event vanishes with it; if it commits, delivery is guaranteed at-least-once
 * (a poller sweeps undelivered rows into the delivery queue). Retrofitting this later would
 * touch every write path, which is exactly why it lands now.
 *
 * `webhook_endpoints`: where a tenant wants events POSTed. The signing secret is generated by
 * us, shown ONCE at creation, and stored here tenant-scoped under FORCE RLS — it must be
 * READABLE (HMAC signing needs the raw secret; a hash can't sign), so RLS is the boundary.
 *
 * Both tables: tenant RLS + the provisioner's scoped read (delivery discovery is cross-tenant),
 * in the raw-SQL RLS migration.
 */

export const webhookEndpoints = pgTable(
  "webhook_endpoints",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id").notNull().$type<TenantId>(),
    // ADR-0004: an endpoint belongs to one application-environment (events fire per environment).
    // Nullable during the two-step backfill; new endpoints always set both.
    applicationId: uuid("application_id")
      .references(() => applications.id, { onDelete: "cascade" })
      .$type<ApplicationId>(),
    environmentId: uuid("environment_id")
      .references(() => environments.id, { onDelete: "cascade" })
      .$type<EnvironmentId>(),
    url: text("url").notNull(),
    /** whsec_… signing secret — shown once at creation, needed raw for HMAC. RLS-guarded. */
    secret: text("secret").notNull(),
    status: text("status").notNull().default("active"), // active | disabled
    description: text("description"),
    ...timestamps,
  },
  (t) => [
    index("idx_webhook_endpoints_tenant").on(t.tenantId),
    foreignKey({
      columns: [t.applicationId, t.tenantId],
      foreignColumns: [applications.id, applications.tenantId],
      name: "webhook_endpoints_application_tenant_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [t.environmentId, t.applicationId, t.tenantId],
      foreignColumns: [
        environments.id,
        environments.applicationId,
        environments.tenantId,
      ],
      name: "webhook_endpoints_environment_application_tenant_fk",
    }).onDelete("cascade"),
  ],
);

export const outboxEvents = pgTable(
  "outbox_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id").notNull().$type<TenantId>(),
    applicationId: uuid("application_id")
      .references(() => applications.id, { onDelete: "cascade" })
      .$type<ApplicationId>(),
    environmentId: uuid("environment_id")
      .references(() => environments.id, { onDelete: "cascade" })
      .$type<EnvironmentId>(),
    eventType: text("event_type").notNull(), // e.g. message.updated | topup.succeeded
    payload: jsonb("payload").notNull(),
    /** Delivery bookkeeping: null until every active endpoint acked (or attempts exhausted). */
    deliveredAt: timestamp("delivered_at", { withTimezone: true }),
    attempts: integer("attempts").notNull().default(0),
    ...timestamps,
  },
  (t) => [
    // The poller scans ONLY undelivered rows — partial index keeps it cheap forever.
    index("idx_outbox_undelivered")
      .on(t.createdAt)
      .where(sql`delivered_at IS NULL`),
    foreignKey({
      columns: [t.applicationId, t.tenantId],
      foreignColumns: [applications.id, applications.tenantId],
      name: "outbox_events_application_tenant_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [t.environmentId, t.applicationId, t.tenantId],
      foreignColumns: [
        environments.id,
        environments.applicationId,
        environments.tenantId,
      ],
      name: "outbox_events_environment_application_tenant_fk",
    }).onDelete("cascade"),
  ],
);

export type WebhookEndpoint = typeof webhookEndpoints.$inferSelect;
export type NewWebhookEndpoint = typeof webhookEndpoints.$inferInsert;
export type OutboxEvent = typeof outboxEvents.$inferSelect;
export type NewOutboxEvent = typeof outboxEvents.$inferInsert;
